events {}

http {
  server {
    listen 80;

    # storage app — strip /storage prefix before forwarding
    location /storage/ {
      proxy_pass http://host.docker.internal:4000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_buffer_size       128k;              # Buffer for response headers (first part of response)
      proxy_buffers           4 256k;            # Number × size of buffers for the response body
      proxy_busy_buffers_size 256k;              # Max buffer size actively being sent to client
    }

    # campus app — everything else
    location / {
      proxy_pass http://host.docker.internal:3000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      
      proxy_buffer_size       128k;              # Buffer for response headers (first part of response)
      proxy_buffers           4 256k;            # Number × size of buffers for the response body
      proxy_busy_buffers_size 256k;              # Max buffer size actively being sent to client
    }
  }
}