/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as guestRouteRouteImport } from './routes/(guest)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as publiclawsuitPagesRouteRouteImport } from './routes/(public)/(lawsuit-pages)/route'
import { Route as publiclandingPagesRouteRouteImport } from './routes/(public)/(landing-pages)/route'
import { Route as authenticatednewUsersRouteRouteImport } from './routes/(authenticated)/(new-users)/route'
import { Route as publiclandingPagesIndexRouteImport } from './routes/(public)/(landing-pages)/index'
import { Route as guestSigninIndexRouteImport } from './routes/(guest)/signin/index'
import { Route as authenticatedSettingsIndexRouteImport } from './routes/(authenticated)/settings/index'
import { Route as authenticatedRedirectSigninIndexRouteImport } from './routes/(authenticated)/redirect-signin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedexistingUsersUsernameRouteRouteImport } from './routes/(authenticated)/(existing-users)/$username/route'
import { Route as publiclawsuitPagesTermsAndConditionsIndexRouteImport } from './routes/(public)/(lawsuit-pages)/terms-and-conditions/index'
import { Route as publiclawsuitPagesRefundPolicyIndexRouteImport } from './routes/(public)/(lawsuit-pages)/refund-policy/index'
import { Route as publiclawsuitPagesPrivacyPolicyIndexRouteImport } from './routes/(public)/(lawsuit-pages)/privacy-policy/index'
import { Route as publiclawsuitPagesDisclaimerIndexRouteImport } from './routes/(public)/(lawsuit-pages)/disclaimer/index'
import { Route as publiclandingPagesResourcesIndexRouteImport } from './routes/(public)/(landing-pages)/resources/index'
import { Route as publiclandingPagesContactUsIndexRouteImport } from './routes/(public)/(landing-pages)/contact-us/index'
import { Route as publiclandingPagesAboutUsIndexRouteImport } from './routes/(public)/(landing-pages)/about-us/index'
import { Route as authenticatednewUsersWelcomeIndexRouteImport } from './routes/(authenticated)/(new-users)/welcome/index'
import { Route as authenticatedexistingUsersUsernameDashboardIndexRouteImport } from './routes/(authenticated)/(existing-users)/$username/dashboard/index'
import { Route as authenticatedexistingUsersUsernameCoursesIndexRouteImport } from './routes/(authenticated)/(existing-users)/$username/courses/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestRouteRoute = guestRouteRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const publiclawsuitPagesRouteRoute = publiclawsuitPagesRouteRouteImport.update({
  id: '/(lawsuit-pages)',
  getParentRoute: () => publicRouteRoute,
} as any)
const publiclandingPagesRouteRoute = publiclandingPagesRouteRouteImport.update({
  id: '/(landing-pages)',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatednewUsersRouteRoute =
  authenticatednewUsersRouteRouteImport.update({
    id: '/(new-users)',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const publiclandingPagesIndexRoute = publiclandingPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publiclandingPagesRouteRoute,
} as any)
const guestSigninIndexRoute = guestSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => guestRouteRoute,
} as any)
const authenticatedSettingsIndexRoute =
  authenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedRedirectSigninIndexRoute =
  authenticatedRedirectSigninIndexRouteImport.update({
    id: '/redirect-signin/',
    path: '/redirect-signin/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedexistingUsersUsernameRouteRoute =
  authenticatedexistingUsersUsernameRouteRouteImport.update({
    id: '/(existing-users)/$username',
    path: '/$username',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const publiclawsuitPagesTermsAndConditionsIndexRoute =
  publiclawsuitPagesTermsAndConditionsIndexRouteImport.update({
    id: '/terms-and-conditions/',
    path: '/terms-and-conditions/',
    getParentRoute: () => publiclawsuitPagesRouteRoute,
  } as any)
const publiclawsuitPagesRefundPolicyIndexRoute =
  publiclawsuitPagesRefundPolicyIndexRouteImport.update({
    id: '/refund-policy/',
    path: '/refund-policy/',
    getParentRoute: () => publiclawsuitPagesRouteRoute,
  } as any)
const publiclawsuitPagesPrivacyPolicyIndexRoute =
  publiclawsuitPagesPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => publiclawsuitPagesRouteRoute,
  } as any)
const publiclawsuitPagesDisclaimerIndexRoute =
  publiclawsuitPagesDisclaimerIndexRouteImport.update({
    id: '/disclaimer/',
    path: '/disclaimer/',
    getParentRoute: () => publiclawsuitPagesRouteRoute,
  } as any)
const publiclandingPagesResourcesIndexRoute =
  publiclandingPagesResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => publiclandingPagesRouteRoute,
  } as any)
const publiclandingPagesContactUsIndexRoute =
  publiclandingPagesContactUsIndexRouteImport.update({
    id: '/contact-us/',
    path: '/contact-us/',
    getParentRoute: () => publiclandingPagesRouteRoute,
  } as any)
const publiclandingPagesAboutUsIndexRoute =
  publiclandingPagesAboutUsIndexRouteImport.update({
    id: '/about-us/',
    path: '/about-us/',
    getParentRoute: () => publiclandingPagesRouteRoute,
  } as any)
const authenticatednewUsersWelcomeIndexRoute =
  authenticatednewUsersWelcomeIndexRouteImport.update({
    id: '/welcome/',
    path: '/welcome/',
    getParentRoute: () => authenticatednewUsersRouteRoute,
  } as any)
const authenticatedexistingUsersUsernameDashboardIndexRoute =
  authenticatedexistingUsersUsernameDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => authenticatedexistingUsersUsernameRouteRoute,
  } as any)
const authenticatedexistingUsersUsernameCoursesIndexRoute =
  authenticatedexistingUsersUsernameCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => authenticatedexistingUsersUsernameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/upload-image': typeof ApiUploadImageRoute
  '/$username': typeof authenticatedexistingUsersUsernameRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/redirect-signin/': typeof authenticatedRedirectSigninIndexRoute
  '/settings/': typeof authenticatedSettingsIndexRoute
  '/signin/': typeof guestSigninIndexRoute
  '/': typeof publiclandingPagesIndexRoute
  '/welcome/': typeof authenticatednewUsersWelcomeIndexRoute
  '/about-us/': typeof publiclandingPagesAboutUsIndexRoute
  '/contact-us/': typeof publiclandingPagesContactUsIndexRoute
  '/resources/': typeof publiclandingPagesResourcesIndexRoute
  '/disclaimer/': typeof publiclawsuitPagesDisclaimerIndexRoute
  '/privacy-policy/': typeof publiclawsuitPagesPrivacyPolicyIndexRoute
  '/refund-policy/': typeof publiclawsuitPagesRefundPolicyIndexRoute
  '/terms-and-conditions/': typeof publiclawsuitPagesTermsAndConditionsIndexRoute
  '/$username/courses/': typeof authenticatedexistingUsersUsernameCoursesIndexRoute
  '/$username/dashboard/': typeof authenticatedexistingUsersUsernameDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/api/upload-image': typeof ApiUploadImageRoute
  '/$username': typeof authenticatedexistingUsersUsernameRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/redirect-signin': typeof authenticatedRedirectSigninIndexRoute
  '/settings': typeof authenticatedSettingsIndexRoute
  '/signin': typeof guestSigninIndexRoute
  '/': typeof publiclandingPagesIndexRoute
  '/welcome': typeof authenticatednewUsersWelcomeIndexRoute
  '/about-us': typeof publiclandingPagesAboutUsIndexRoute
  '/contact-us': typeof publiclandingPagesContactUsIndexRoute
  '/resources': typeof publiclandingPagesResourcesIndexRoute
  '/disclaimer': typeof publiclawsuitPagesDisclaimerIndexRoute
  '/privacy-policy': typeof publiclawsuitPagesPrivacyPolicyIndexRoute
  '/refund-policy': typeof publiclawsuitPagesRefundPolicyIndexRoute
  '/terms-and-conditions': typeof publiclawsuitPagesTermsAndConditionsIndexRoute
  '/$username/courses': typeof authenticatedexistingUsersUsernameCoursesIndexRoute
  '/$username/dashboard': typeof authenticatedexistingUsersUsernameDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(guest)': typeof guestRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/(new-users)': typeof authenticatednewUsersRouteRouteWithChildren
  '/(public)/(landing-pages)': typeof publiclandingPagesRouteRouteWithChildren
  '/(public)/(lawsuit-pages)': typeof publiclawsuitPagesRouteRouteWithChildren
  '/api/upload-image': typeof ApiUploadImageRoute
  '/(authenticated)/(existing-users)/$username': typeof authenticatedexistingUsersUsernameRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(authenticated)/redirect-signin/': typeof authenticatedRedirectSigninIndexRoute
  '/(authenticated)/settings/': typeof authenticatedSettingsIndexRoute
  '/(guest)/signin/': typeof guestSigninIndexRoute
  '/(public)/(landing-pages)/': typeof publiclandingPagesIndexRoute
  '/(authenticated)/(new-users)/welcome/': typeof authenticatednewUsersWelcomeIndexRoute
  '/(public)/(landing-pages)/about-us/': typeof publiclandingPagesAboutUsIndexRoute
  '/(public)/(landing-pages)/contact-us/': typeof publiclandingPagesContactUsIndexRoute
  '/(public)/(landing-pages)/resources/': typeof publiclandingPagesResourcesIndexRoute
  '/(public)/(lawsuit-pages)/disclaimer/': typeof publiclawsuitPagesDisclaimerIndexRoute
  '/(public)/(lawsuit-pages)/privacy-policy/': typeof publiclawsuitPagesPrivacyPolicyIndexRoute
  '/(public)/(lawsuit-pages)/refund-policy/': typeof publiclawsuitPagesRefundPolicyIndexRoute
  '/(public)/(lawsuit-pages)/terms-and-conditions/': typeof publiclawsuitPagesTermsAndConditionsIndexRoute
  '/(authenticated)/(existing-users)/$username/courses/': typeof authenticatedexistingUsersUsernameCoursesIndexRoute
  '/(authenticated)/(existing-users)/$username/dashboard/': typeof authenticatedexistingUsersUsernameDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/upload-image'
    | '/$username'
    | '/api/auth/$'
    | '/redirect-signin/'
    | '/settings/'
    | '/signin/'
    | '/'
    | '/welcome/'
    | '/about-us/'
    | '/contact-us/'
    | '/resources/'
    | '/disclaimer/'
    | '/privacy-policy/'
    | '/refund-policy/'
    | '/terms-and-conditions/'
    | '/$username/courses/'
    | '/$username/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/upload-image'
    | '/$username'
    | '/api/auth/$'
    | '/redirect-signin'
    | '/settings'
    | '/signin'
    | '/'
    | '/welcome'
    | '/about-us'
    | '/contact-us'
    | '/resources'
    | '/disclaimer'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/$username/courses'
    | '/$username/dashboard'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(guest)'
    | '/(public)'
    | '/(authenticated)/(new-users)'
    | '/(public)/(landing-pages)'
    | '/(public)/(lawsuit-pages)'
    | '/api/upload-image'
    | '/(authenticated)/(existing-users)/$username'
    | '/api/auth/$'
    | '/(authenticated)/redirect-signin/'
    | '/(authenticated)/settings/'
    | '/(guest)/signin/'
    | '/(public)/(landing-pages)/'
    | '/(authenticated)/(new-users)/welcome/'
    | '/(public)/(landing-pages)/about-us/'
    | '/(public)/(landing-pages)/contact-us/'
    | '/(public)/(landing-pages)/resources/'
    | '/(public)/(lawsuit-pages)/disclaimer/'
    | '/(public)/(lawsuit-pages)/privacy-policy/'
    | '/(public)/(lawsuit-pages)/refund-policy/'
    | '/(public)/(lawsuit-pages)/terms-and-conditions/'
    | '/(authenticated)/(existing-users)/$username/courses/'
    | '/(authenticated)/(existing-users)/$username/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  guestRouteRoute: typeof guestRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiUploadImageRoute: typeof ApiUploadImageRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(lawsuit-pages)': {
      id: '/(public)/(lawsuit-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publiclawsuitPagesRouteRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(landing-pages)': {
      id: '/(public)/(landing-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publiclandingPagesRouteRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/(new-users)': {
      id: '/(authenticated)/(new-users)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatednewUsersRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/(landing-pages)/': {
      id: '/(public)/(landing-pages)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publiclandingPagesIndexRouteImport
      parentRoute: typeof publiclandingPagesRouteRoute
    }
    '/(guest)/signin/': {
      id: '/(guest)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof guestSigninIndexRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/(authenticated)/settings/': {
      id: '/(authenticated)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof authenticatedSettingsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/redirect-signin/': {
      id: '/(authenticated)/redirect-signin/'
      path: '/redirect-signin'
      fullPath: '/redirect-signin/'
      preLoaderRoute: typeof authenticatedRedirectSigninIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/(existing-users)/$username': {
      id: '/(authenticated)/(existing-users)/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof authenticatedexistingUsersUsernameRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/(lawsuit-pages)/terms-and-conditions/': {
      id: '/(public)/(lawsuit-pages)/terms-and-conditions/'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions/'
      preLoaderRoute: typeof publiclawsuitPagesTermsAndConditionsIndexRouteImport
      parentRoute: typeof publiclawsuitPagesRouteRoute
    }
    '/(public)/(lawsuit-pages)/refund-policy/': {
      id: '/(public)/(lawsuit-pages)/refund-policy/'
      path: '/refund-policy'
      fullPath: '/refund-policy/'
      preLoaderRoute: typeof publiclawsuitPagesRefundPolicyIndexRouteImport
      parentRoute: typeof publiclawsuitPagesRouteRoute
    }
    '/(public)/(lawsuit-pages)/privacy-policy/': {
      id: '/(public)/(lawsuit-pages)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof publiclawsuitPagesPrivacyPolicyIndexRouteImport
      parentRoute: typeof publiclawsuitPagesRouteRoute
    }
    '/(public)/(lawsuit-pages)/disclaimer/': {
      id: '/(public)/(lawsuit-pages)/disclaimer/'
      path: '/disclaimer'
      fullPath: '/disclaimer/'
      preLoaderRoute: typeof publiclawsuitPagesDisclaimerIndexRouteImport
      parentRoute: typeof publiclawsuitPagesRouteRoute
    }
    '/(public)/(landing-pages)/resources/': {
      id: '/(public)/(landing-pages)/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof publiclandingPagesResourcesIndexRouteImport
      parentRoute: typeof publiclandingPagesRouteRoute
    }
    '/(public)/(landing-pages)/contact-us/': {
      id: '/(public)/(landing-pages)/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us/'
      preLoaderRoute: typeof publiclandingPagesContactUsIndexRouteImport
      parentRoute: typeof publiclandingPagesRouteRoute
    }
    '/(public)/(landing-pages)/about-us/': {
      id: '/(public)/(landing-pages)/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof publiclandingPagesAboutUsIndexRouteImport
      parentRoute: typeof publiclandingPagesRouteRoute
    }
    '/(authenticated)/(new-users)/welcome/': {
      id: '/(authenticated)/(new-users)/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof authenticatednewUsersWelcomeIndexRouteImport
      parentRoute: typeof authenticatednewUsersRouteRoute
    }
    '/(authenticated)/(existing-users)/$username/dashboard/': {
      id: '/(authenticated)/(existing-users)/$username/dashboard/'
      path: '/dashboard'
      fullPath: '/$username/dashboard/'
      preLoaderRoute: typeof authenticatedexistingUsersUsernameDashboardIndexRouteImport
      parentRoute: typeof authenticatedexistingUsersUsernameRouteRoute
    }
    '/(authenticated)/(existing-users)/$username/courses/': {
      id: '/(authenticated)/(existing-users)/$username/courses/'
      path: '/courses'
      fullPath: '/$username/courses/'
      preLoaderRoute: typeof authenticatedexistingUsersUsernameCoursesIndexRouteImport
      parentRoute: typeof authenticatedexistingUsersUsernameRouteRoute
    }
  }
}

interface authenticatednewUsersRouteRouteChildren {
  authenticatednewUsersWelcomeIndexRoute: typeof authenticatednewUsersWelcomeIndexRoute
}

const authenticatednewUsersRouteRouteChildren: authenticatednewUsersRouteRouteChildren =
  {
    authenticatednewUsersWelcomeIndexRoute:
      authenticatednewUsersWelcomeIndexRoute,
  }

const authenticatednewUsersRouteRouteWithChildren =
  authenticatednewUsersRouteRoute._addFileChildren(
    authenticatednewUsersRouteRouteChildren,
  )

interface authenticatedexistingUsersUsernameRouteRouteChildren {
  authenticatedexistingUsersUsernameCoursesIndexRoute: typeof authenticatedexistingUsersUsernameCoursesIndexRoute
  authenticatedexistingUsersUsernameDashboardIndexRoute: typeof authenticatedexistingUsersUsernameDashboardIndexRoute
}

const authenticatedexistingUsersUsernameRouteRouteChildren: authenticatedexistingUsersUsernameRouteRouteChildren =
  {
    authenticatedexistingUsersUsernameCoursesIndexRoute:
      authenticatedexistingUsersUsernameCoursesIndexRoute,
    authenticatedexistingUsersUsernameDashboardIndexRoute:
      authenticatedexistingUsersUsernameDashboardIndexRoute,
  }

const authenticatedexistingUsersUsernameRouteRouteWithChildren =
  authenticatedexistingUsersUsernameRouteRoute._addFileChildren(
    authenticatedexistingUsersUsernameRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatednewUsersRouteRoute: typeof authenticatednewUsersRouteRouteWithChildren
  authenticatedexistingUsersUsernameRouteRoute: typeof authenticatedexistingUsersUsernameRouteRouteWithChildren
  authenticatedRedirectSigninIndexRoute: typeof authenticatedRedirectSigninIndexRoute
  authenticatedSettingsIndexRoute: typeof authenticatedSettingsIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatednewUsersRouteRoute: authenticatednewUsersRouteRouteWithChildren,
  authenticatedexistingUsersUsernameRouteRoute:
    authenticatedexistingUsersUsernameRouteRouteWithChildren,
  authenticatedRedirectSigninIndexRoute: authenticatedRedirectSigninIndexRoute,
  authenticatedSettingsIndexRoute: authenticatedSettingsIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface guestRouteRouteChildren {
  guestSigninIndexRoute: typeof guestSigninIndexRoute
}

const guestRouteRouteChildren: guestRouteRouteChildren = {
  guestSigninIndexRoute: guestSigninIndexRoute,
}

const guestRouteRouteWithChildren = guestRouteRoute._addFileChildren(
  guestRouteRouteChildren,
)

interface publiclandingPagesRouteRouteChildren {
  publiclandingPagesIndexRoute: typeof publiclandingPagesIndexRoute
  publiclandingPagesAboutUsIndexRoute: typeof publiclandingPagesAboutUsIndexRoute
  publiclandingPagesContactUsIndexRoute: typeof publiclandingPagesContactUsIndexRoute
  publiclandingPagesResourcesIndexRoute: typeof publiclandingPagesResourcesIndexRoute
}

const publiclandingPagesRouteRouteChildren: publiclandingPagesRouteRouteChildren =
  {
    publiclandingPagesIndexRoute: publiclandingPagesIndexRoute,
    publiclandingPagesAboutUsIndexRoute: publiclandingPagesAboutUsIndexRoute,
    publiclandingPagesContactUsIndexRoute:
      publiclandingPagesContactUsIndexRoute,
    publiclandingPagesResourcesIndexRoute:
      publiclandingPagesResourcesIndexRoute,
  }

const publiclandingPagesRouteRouteWithChildren =
  publiclandingPagesRouteRoute._addFileChildren(
    publiclandingPagesRouteRouteChildren,
  )

interface publiclawsuitPagesRouteRouteChildren {
  publiclawsuitPagesDisclaimerIndexRoute: typeof publiclawsuitPagesDisclaimerIndexRoute
  publiclawsuitPagesPrivacyPolicyIndexRoute: typeof publiclawsuitPagesPrivacyPolicyIndexRoute
  publiclawsuitPagesRefundPolicyIndexRoute: typeof publiclawsuitPagesRefundPolicyIndexRoute
  publiclawsuitPagesTermsAndConditionsIndexRoute: typeof publiclawsuitPagesTermsAndConditionsIndexRoute
}

const publiclawsuitPagesRouteRouteChildren: publiclawsuitPagesRouteRouteChildren =
  {
    publiclawsuitPagesDisclaimerIndexRoute:
      publiclawsuitPagesDisclaimerIndexRoute,
    publiclawsuitPagesPrivacyPolicyIndexRoute:
      publiclawsuitPagesPrivacyPolicyIndexRoute,
    publiclawsuitPagesRefundPolicyIndexRoute:
      publiclawsuitPagesRefundPolicyIndexRoute,
    publiclawsuitPagesTermsAndConditionsIndexRoute:
      publiclawsuitPagesTermsAndConditionsIndexRoute,
  }

const publiclawsuitPagesRouteRouteWithChildren =
  publiclawsuitPagesRouteRoute._addFileChildren(
    publiclawsuitPagesRouteRouteChildren,
  )

interface publicRouteRouteChildren {
  publiclandingPagesRouteRoute: typeof publiclandingPagesRouteRouteWithChildren
  publiclawsuitPagesRouteRoute: typeof publiclawsuitPagesRouteRouteWithChildren
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publiclandingPagesRouteRoute: publiclandingPagesRouteRouteWithChildren,
  publiclawsuitPagesRouteRoute: publiclawsuitPagesRouteRouteWithChildren,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  guestRouteRoute: guestRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiUploadImageRoute: ApiUploadImageRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
