name: sanjib-academy-test

networks:
  sanjib-academy-test:
    driver: bridge

services:
  sanjib-academy-test-database:
    container_name: sanjib-academy-test-database
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    networks:
      - sanjib-academy-test

  # sanjib-academy-test-cache:
  #   container_name: sanjib-academy-test-cache
  #   image: redis/redis-stack:7.4.0-v8
  #   ports:
  #     - 6379:6379
  #     - 8001:8001
  #   networks:
  #     - sanjib-academy-test
