/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as guestRouteRouteImport } from './routes/(guest)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publiclawsuitPagesRouteRouteImport } from './routes/(public)/(lawsuit-pages)/route'
import { Route as publiclandingPagesRouteRouteImport } from './routes/(public)/(landing-pages)/route'
import { Route as authenticatedexistingUserRouteRouteImport } from './routes/(authenticated)/(existing-user)/route'
import { Route as publiclandingPagesIndexRouteImport } from './routes/(public)/(landing-pages)/index'
import { Route as guestSigninIndexRouteImport } from './routes/(guest)/signin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatednewUserRouterRouteImport } from './routes/(authenticated)/(new-user)/router'
import { Route as publiclawsuitPagesTermsAndConditionsIndexRouteImport } from './routes/(public)/(lawsuit-pages)/terms-and-conditions/index'
import { Route as publiclawsuitPagesRefundPolicyIndexRouteImport } from './routes/(public)/(lawsuit-pages)/refund-policy/index'
import { Route as publiclawsuitPagesPrivacyPolicyIndexRouteImport } from './routes/(public)/(lawsuit-pages)/privacy-policy/index'
import { Route as publiclawsuitPagesDisclaimerIndexRouteImport } from './routes/(public)/(lawsuit-pages)/disclaimer/index'
import { Route as publiclandingPagesCoursesIndexRouteImport } from './routes/(public)/(landing-pages)/courses/index'
import { Route as publiclandingPagesContactUsIndexRouteImport } from './routes/(public)/(landing-pages)/contact-us/index'
import { Route as publiclandingPagesAboutUsIndexRouteImport } from './routes/(public)/(landing-pages)/about-us/index'
import { Route as authenticatednewUserWelcomeIndexRouteImport } from './routes/(authenticated)/(new-user)/welcome/index'
import { Route as authenticatedexistingUserDashboardIndexRouteImport } from './routes/(authenticated)/(existing-user)/dashboard/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestRouteRoute = guestRouteRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publiclawsuitPagesRouteRoute = publiclawsuitPagesRouteRouteImport.update({
  id: '/(lawsuit-pages)',
  getParentRoute: () => publicRouteRoute,
} as any)
const publiclandingPagesRouteRoute = publiclandingPagesRouteRouteImport.update({
  id: '/(landing-pages)',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedexistingUserRouteRoute =
  authenticatedexistingUserRouteRouteImport.update({
    id: '/(existing-user)',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const publiclandingPagesIndexRoute = publiclandingPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publiclandingPagesRouteRoute,
} as any)
const guestSigninIndexRoute = guestSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => guestRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatednewUserRouterRoute =
  authenticatednewUserRouterRouteImport.update({
    id: '/(new-user)/router',
    path: '/router',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const publiclawsuitPagesTermsAndConditionsIndexRoute =
  publiclawsuitPagesTermsAndConditionsIndexRouteImport.update({
    id: '/terms-and-conditions/',
    path: '/terms-and-conditions/',
    getParentRoute: () => publiclawsuitPagesRouteRoute,
  } as any)
const publiclawsuitPagesRefundPolicyIndexRoute =
  publiclawsuitPagesRefundPolicyIndexRouteImport.update({
    id: '/refund-policy/',
    path: '/refund-policy/',
    getParentRoute: () => publiclawsuitPagesRouteRoute,
  } as any)
const publiclawsuitPagesPrivacyPolicyIndexRoute =
  publiclawsuitPagesPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => publiclawsuitPagesRouteRoute,
  } as any)
const publiclawsuitPagesDisclaimerIndexRoute =
  publiclawsuitPagesDisclaimerIndexRouteImport.update({
    id: '/disclaimer/',
    path: '/disclaimer/',
    getParentRoute: () => publiclawsuitPagesRouteRoute,
  } as any)
const publiclandingPagesCoursesIndexRoute =
  publiclandingPagesCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => publiclandingPagesRouteRoute,
  } as any)
const publiclandingPagesContactUsIndexRoute =
  publiclandingPagesContactUsIndexRouteImport.update({
    id: '/contact-us/',
    path: '/contact-us/',
    getParentRoute: () => publiclandingPagesRouteRoute,
  } as any)
const publiclandingPagesAboutUsIndexRoute =
  publiclandingPagesAboutUsIndexRouteImport.update({
    id: '/about-us/',
    path: '/about-us/',
    getParentRoute: () => publiclandingPagesRouteRoute,
  } as any)
const authenticatednewUserWelcomeIndexRoute =
  authenticatednewUserWelcomeIndexRouteImport.update({
    id: '/(new-user)/welcome/',
    path: '/welcome/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedexistingUserDashboardIndexRoute =
  authenticatedexistingUserDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => authenticatedexistingUserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/router': typeof authenticatednewUserRouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/signin/': typeof guestSigninIndexRoute
  '/': typeof publiclandingPagesIndexRoute
  '/dashboard/': typeof authenticatedexistingUserDashboardIndexRoute
  '/welcome/': typeof authenticatednewUserWelcomeIndexRoute
  '/about-us/': typeof publiclandingPagesAboutUsIndexRoute
  '/contact-us/': typeof publiclandingPagesContactUsIndexRoute
  '/courses/': typeof publiclandingPagesCoursesIndexRoute
  '/disclaimer/': typeof publiclawsuitPagesDisclaimerIndexRoute
  '/privacy-policy/': typeof publiclawsuitPagesPrivacyPolicyIndexRoute
  '/refund-policy/': typeof publiclawsuitPagesRefundPolicyIndexRoute
  '/terms-and-conditions/': typeof publiclawsuitPagesTermsAndConditionsIndexRoute
}
export interface FileRoutesByTo {
  '/router': typeof authenticatednewUserRouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/signin': typeof guestSigninIndexRoute
  '/': typeof publiclandingPagesIndexRoute
  '/dashboard': typeof authenticatedexistingUserDashboardIndexRoute
  '/welcome': typeof authenticatednewUserWelcomeIndexRoute
  '/about-us': typeof publiclandingPagesAboutUsIndexRoute
  '/contact-us': typeof publiclandingPagesContactUsIndexRoute
  '/courses': typeof publiclandingPagesCoursesIndexRoute
  '/disclaimer': typeof publiclawsuitPagesDisclaimerIndexRoute
  '/privacy-policy': typeof publiclawsuitPagesPrivacyPolicyIndexRoute
  '/refund-policy': typeof publiclawsuitPagesRefundPolicyIndexRoute
  '/terms-and-conditions': typeof publiclawsuitPagesTermsAndConditionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(guest)': typeof guestRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/(existing-user)': typeof authenticatedexistingUserRouteRouteWithChildren
  '/(public)/(landing-pages)': typeof publiclandingPagesRouteRouteWithChildren
  '/(public)/(lawsuit-pages)': typeof publiclawsuitPagesRouteRouteWithChildren
  '/(authenticated)/(new-user)/router': typeof authenticatednewUserRouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(guest)/signin/': typeof guestSigninIndexRoute
  '/(public)/(landing-pages)/': typeof publiclandingPagesIndexRoute
  '/(authenticated)/(existing-user)/dashboard/': typeof authenticatedexistingUserDashboardIndexRoute
  '/(authenticated)/(new-user)/welcome/': typeof authenticatednewUserWelcomeIndexRoute
  '/(public)/(landing-pages)/about-us/': typeof publiclandingPagesAboutUsIndexRoute
  '/(public)/(landing-pages)/contact-us/': typeof publiclandingPagesContactUsIndexRoute
  '/(public)/(landing-pages)/courses/': typeof publiclandingPagesCoursesIndexRoute
  '/(public)/(lawsuit-pages)/disclaimer/': typeof publiclawsuitPagesDisclaimerIndexRoute
  '/(public)/(lawsuit-pages)/privacy-policy/': typeof publiclawsuitPagesPrivacyPolicyIndexRoute
  '/(public)/(lawsuit-pages)/refund-policy/': typeof publiclawsuitPagesRefundPolicyIndexRoute
  '/(public)/(lawsuit-pages)/terms-and-conditions/': typeof publiclawsuitPagesTermsAndConditionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/router'
    | '/api/auth/$'
    | '/signin/'
    | '/'
    | '/dashboard/'
    | '/welcome/'
    | '/about-us/'
    | '/contact-us/'
    | '/courses/'
    | '/disclaimer/'
    | '/privacy-policy/'
    | '/refund-policy/'
    | '/terms-and-conditions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/router'
    | '/api/auth/$'
    | '/signin'
    | '/'
    | '/dashboard'
    | '/welcome'
    | '/about-us'
    | '/contact-us'
    | '/courses'
    | '/disclaimer'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(guest)'
    | '/(public)'
    | '/(authenticated)/(existing-user)'
    | '/(public)/(landing-pages)'
    | '/(public)/(lawsuit-pages)'
    | '/(authenticated)/(new-user)/router'
    | '/api/auth/$'
    | '/(guest)/signin/'
    | '/(public)/(landing-pages)/'
    | '/(authenticated)/(existing-user)/dashboard/'
    | '/(authenticated)/(new-user)/welcome/'
    | '/(public)/(landing-pages)/about-us/'
    | '/(public)/(landing-pages)/contact-us/'
    | '/(public)/(landing-pages)/courses/'
    | '/(public)/(lawsuit-pages)/disclaimer/'
    | '/(public)/(lawsuit-pages)/privacy-policy/'
    | '/(public)/(lawsuit-pages)/refund-policy/'
    | '/(public)/(lawsuit-pages)/terms-and-conditions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  guestRouteRoute: typeof guestRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(lawsuit-pages)': {
      id: '/(public)/(lawsuit-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publiclawsuitPagesRouteRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(landing-pages)': {
      id: '/(public)/(landing-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publiclandingPagesRouteRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/(existing-user)': {
      id: '/(authenticated)/(existing-user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedexistingUserRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/(landing-pages)/': {
      id: '/(public)/(landing-pages)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publiclandingPagesIndexRouteImport
      parentRoute: typeof publiclandingPagesRouteRoute
    }
    '/(guest)/signin/': {
      id: '/(guest)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof guestSigninIndexRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/(new-user)/router': {
      id: '/(authenticated)/(new-user)/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof authenticatednewUserRouterRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/(lawsuit-pages)/terms-and-conditions/': {
      id: '/(public)/(lawsuit-pages)/terms-and-conditions/'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions/'
      preLoaderRoute: typeof publiclawsuitPagesTermsAndConditionsIndexRouteImport
      parentRoute: typeof publiclawsuitPagesRouteRoute
    }
    '/(public)/(lawsuit-pages)/refund-policy/': {
      id: '/(public)/(lawsuit-pages)/refund-policy/'
      path: '/refund-policy'
      fullPath: '/refund-policy/'
      preLoaderRoute: typeof publiclawsuitPagesRefundPolicyIndexRouteImport
      parentRoute: typeof publiclawsuitPagesRouteRoute
    }
    '/(public)/(lawsuit-pages)/privacy-policy/': {
      id: '/(public)/(lawsuit-pages)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof publiclawsuitPagesPrivacyPolicyIndexRouteImport
      parentRoute: typeof publiclawsuitPagesRouteRoute
    }
    '/(public)/(lawsuit-pages)/disclaimer/': {
      id: '/(public)/(lawsuit-pages)/disclaimer/'
      path: '/disclaimer'
      fullPath: '/disclaimer/'
      preLoaderRoute: typeof publiclawsuitPagesDisclaimerIndexRouteImport
      parentRoute: typeof publiclawsuitPagesRouteRoute
    }
    '/(public)/(landing-pages)/courses/': {
      id: '/(public)/(landing-pages)/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof publiclandingPagesCoursesIndexRouteImport
      parentRoute: typeof publiclandingPagesRouteRoute
    }
    '/(public)/(landing-pages)/contact-us/': {
      id: '/(public)/(landing-pages)/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us/'
      preLoaderRoute: typeof publiclandingPagesContactUsIndexRouteImport
      parentRoute: typeof publiclandingPagesRouteRoute
    }
    '/(public)/(landing-pages)/about-us/': {
      id: '/(public)/(landing-pages)/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof publiclandingPagesAboutUsIndexRouteImport
      parentRoute: typeof publiclandingPagesRouteRoute
    }
    '/(authenticated)/(new-user)/welcome/': {
      id: '/(authenticated)/(new-user)/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof authenticatednewUserWelcomeIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/(existing-user)/dashboard/': {
      id: '/(authenticated)/(existing-user)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedexistingUserDashboardIndexRouteImport
      parentRoute: typeof authenticatedexistingUserRouteRoute
    }
  }
}

interface authenticatedexistingUserRouteRouteChildren {
  authenticatedexistingUserDashboardIndexRoute: typeof authenticatedexistingUserDashboardIndexRoute
}

const authenticatedexistingUserRouteRouteChildren: authenticatedexistingUserRouteRouteChildren =
  {
    authenticatedexistingUserDashboardIndexRoute:
      authenticatedexistingUserDashboardIndexRoute,
  }

const authenticatedexistingUserRouteRouteWithChildren =
  authenticatedexistingUserRouteRoute._addFileChildren(
    authenticatedexistingUserRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedexistingUserRouteRoute: typeof authenticatedexistingUserRouteRouteWithChildren
  authenticatednewUserRouterRoute: typeof authenticatednewUserRouterRoute
  authenticatednewUserWelcomeIndexRoute: typeof authenticatednewUserWelcomeIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedexistingUserRouteRoute:
    authenticatedexistingUserRouteRouteWithChildren,
  authenticatednewUserRouterRoute: authenticatednewUserRouterRoute,
  authenticatednewUserWelcomeIndexRoute: authenticatednewUserWelcomeIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface guestRouteRouteChildren {
  guestSigninIndexRoute: typeof guestSigninIndexRoute
}

const guestRouteRouteChildren: guestRouteRouteChildren = {
  guestSigninIndexRoute: guestSigninIndexRoute,
}

const guestRouteRouteWithChildren = guestRouteRoute._addFileChildren(
  guestRouteRouteChildren,
)

interface publiclandingPagesRouteRouteChildren {
  publiclandingPagesIndexRoute: typeof publiclandingPagesIndexRoute
  publiclandingPagesAboutUsIndexRoute: typeof publiclandingPagesAboutUsIndexRoute
  publiclandingPagesContactUsIndexRoute: typeof publiclandingPagesContactUsIndexRoute
  publiclandingPagesCoursesIndexRoute: typeof publiclandingPagesCoursesIndexRoute
}

const publiclandingPagesRouteRouteChildren: publiclandingPagesRouteRouteChildren =
  {
    publiclandingPagesIndexRoute: publiclandingPagesIndexRoute,
    publiclandingPagesAboutUsIndexRoute: publiclandingPagesAboutUsIndexRoute,
    publiclandingPagesContactUsIndexRoute:
      publiclandingPagesContactUsIndexRoute,
    publiclandingPagesCoursesIndexRoute: publiclandingPagesCoursesIndexRoute,
  }

const publiclandingPagesRouteRouteWithChildren =
  publiclandingPagesRouteRoute._addFileChildren(
    publiclandingPagesRouteRouteChildren,
  )

interface publiclawsuitPagesRouteRouteChildren {
  publiclawsuitPagesDisclaimerIndexRoute: typeof publiclawsuitPagesDisclaimerIndexRoute
  publiclawsuitPagesPrivacyPolicyIndexRoute: typeof publiclawsuitPagesPrivacyPolicyIndexRoute
  publiclawsuitPagesRefundPolicyIndexRoute: typeof publiclawsuitPagesRefundPolicyIndexRoute
  publiclawsuitPagesTermsAndConditionsIndexRoute: typeof publiclawsuitPagesTermsAndConditionsIndexRoute
}

const publiclawsuitPagesRouteRouteChildren: publiclawsuitPagesRouteRouteChildren =
  {
    publiclawsuitPagesDisclaimerIndexRoute:
      publiclawsuitPagesDisclaimerIndexRoute,
    publiclawsuitPagesPrivacyPolicyIndexRoute:
      publiclawsuitPagesPrivacyPolicyIndexRoute,
    publiclawsuitPagesRefundPolicyIndexRoute:
      publiclawsuitPagesRefundPolicyIndexRoute,
    publiclawsuitPagesTermsAndConditionsIndexRoute:
      publiclawsuitPagesTermsAndConditionsIndexRoute,
  }

const publiclawsuitPagesRouteRouteWithChildren =
  publiclawsuitPagesRouteRoute._addFileChildren(
    publiclawsuitPagesRouteRouteChildren,
  )

interface publicRouteRouteChildren {
  publiclandingPagesRouteRoute: typeof publiclandingPagesRouteRouteWithChildren
  publiclawsuitPagesRouteRoute: typeof publiclawsuitPagesRouteRouteWithChildren
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publiclandingPagesRouteRoute: publiclandingPagesRouteRouteWithChildren,
  publiclawsuitPagesRouteRoute: publiclawsuitPagesRouteRouteWithChildren,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  guestRouteRoute: guestRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
