/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as guestRouteRouteImport } from './routes/(guest)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authenticatedexistingUserRouteRouteImport } from './routes/(authenticated)/(existing-user)/route'
import { Route as publicTermsAndConditionsIndexRouteImport } from './routes/(public)/terms-and-conditions/index'
import { Route as publicRefundPolicyIndexRouteImport } from './routes/(public)/refund-policy/index'
import { Route as publicPrivacyPolicyIndexRouteImport } from './routes/(public)/privacy-policy/index'
import { Route as publicCoursesIndexRouteImport } from './routes/(public)/courses/index'
import { Route as guestSigninIndexRouteImport } from './routes/(guest)/signin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatednewUserRouterRouteImport } from './routes/(authenticated)/(new-user)/router'
import { Route as authenticatednewUserWelcomeIndexRouteImport } from './routes/(authenticated)/(new-user)/welcome/index'
import { Route as authenticatedexistingUserDashboardIndexRouteImport } from './routes/(authenticated)/(existing-user)/dashboard/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestRouteRoute = guestRouteRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedexistingUserRouteRoute =
  authenticatedexistingUserRouteRouteImport.update({
    id: '/(existing-user)',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const publicTermsAndConditionsIndexRoute =
  publicTermsAndConditionsIndexRouteImport.update({
    id: '/terms-and-conditions/',
    path: '/terms-and-conditions/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicRefundPolicyIndexRoute = publicRefundPolicyIndexRouteImport.update({
  id: '/refund-policy/',
  path: '/refund-policy/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyPolicyIndexRoute =
  publicPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicCoursesIndexRoute = publicCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => publicRouteRoute,
} as any)
const guestSigninIndexRoute = guestSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => guestRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatednewUserRouterRoute =
  authenticatednewUserRouterRouteImport.update({
    id: '/(new-user)/router',
    path: '/router',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatednewUserWelcomeIndexRoute =
  authenticatednewUserWelcomeIndexRouteImport.update({
    id: '/(new-user)/welcome/',
    path: '/welcome/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedexistingUserDashboardIndexRoute =
  authenticatedexistingUserDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => authenticatedexistingUserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/router': typeof authenticatednewUserRouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/signin/': typeof guestSigninIndexRoute
  '/courses/': typeof publicCoursesIndexRoute
  '/privacy-policy/': typeof publicPrivacyPolicyIndexRoute
  '/refund-policy/': typeof publicRefundPolicyIndexRoute
  '/terms-and-conditions/': typeof publicTermsAndConditionsIndexRoute
  '/dashboard/': typeof authenticatedexistingUserDashboardIndexRoute
  '/welcome/': typeof authenticatednewUserWelcomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/router': typeof authenticatednewUserRouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/signin': typeof guestSigninIndexRoute
  '/courses': typeof publicCoursesIndexRoute
  '/privacy-policy': typeof publicPrivacyPolicyIndexRoute
  '/refund-policy': typeof publicRefundPolicyIndexRoute
  '/terms-and-conditions': typeof publicTermsAndConditionsIndexRoute
  '/dashboard': typeof authenticatedexistingUserDashboardIndexRoute
  '/welcome': typeof authenticatednewUserWelcomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(guest)': typeof guestRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/(existing-user)': typeof authenticatedexistingUserRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/(new-user)/router': typeof authenticatednewUserRouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(guest)/signin/': typeof guestSigninIndexRoute
  '/(public)/courses/': typeof publicCoursesIndexRoute
  '/(public)/privacy-policy/': typeof publicPrivacyPolicyIndexRoute
  '/(public)/refund-policy/': typeof publicRefundPolicyIndexRoute
  '/(public)/terms-and-conditions/': typeof publicTermsAndConditionsIndexRoute
  '/(authenticated)/(existing-user)/dashboard/': typeof authenticatedexistingUserDashboardIndexRoute
  '/(authenticated)/(new-user)/welcome/': typeof authenticatednewUserWelcomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/router'
    | '/api/auth/$'
    | '/signin/'
    | '/courses/'
    | '/privacy-policy/'
    | '/refund-policy/'
    | '/terms-and-conditions/'
    | '/dashboard/'
    | '/welcome/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/router'
    | '/api/auth/$'
    | '/signin'
    | '/courses'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/dashboard'
    | '/welcome'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(guest)'
    | '/(public)'
    | '/(authenticated)/(existing-user)'
    | '/(public)/'
    | '/(authenticated)/(new-user)/router'
    | '/api/auth/$'
    | '/(guest)/signin/'
    | '/(public)/courses/'
    | '/(public)/privacy-policy/'
    | '/(public)/refund-policy/'
    | '/(public)/terms-and-conditions/'
    | '/(authenticated)/(existing-user)/dashboard/'
    | '/(authenticated)/(new-user)/welcome/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  guestRouteRoute: typeof guestRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/(existing-user)': {
      id: '/(authenticated)/(existing-user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedexistingUserRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/terms-and-conditions/': {
      id: '/(public)/terms-and-conditions/'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions/'
      preLoaderRoute: typeof publicTermsAndConditionsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/refund-policy/': {
      id: '/(public)/refund-policy/'
      path: '/refund-policy'
      fullPath: '/refund-policy/'
      preLoaderRoute: typeof publicRefundPolicyIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy-policy/': {
      id: '/(public)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof publicPrivacyPolicyIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/courses/': {
      id: '/(public)/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof publicCoursesIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(guest)/signin/': {
      id: '/(guest)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof guestSigninIndexRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/(new-user)/router': {
      id: '/(authenticated)/(new-user)/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof authenticatednewUserRouterRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/(new-user)/welcome/': {
      id: '/(authenticated)/(new-user)/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof authenticatednewUserWelcomeIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/(existing-user)/dashboard/': {
      id: '/(authenticated)/(existing-user)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedexistingUserDashboardIndexRouteImport
      parentRoute: typeof authenticatedexistingUserRouteRoute
    }
  }
}

interface authenticatedexistingUserRouteRouteChildren {
  authenticatedexistingUserDashboardIndexRoute: typeof authenticatedexistingUserDashboardIndexRoute
}

const authenticatedexistingUserRouteRouteChildren: authenticatedexistingUserRouteRouteChildren =
  {
    authenticatedexistingUserDashboardIndexRoute:
      authenticatedexistingUserDashboardIndexRoute,
  }

const authenticatedexistingUserRouteRouteWithChildren =
  authenticatedexistingUserRouteRoute._addFileChildren(
    authenticatedexistingUserRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedexistingUserRouteRoute: typeof authenticatedexistingUserRouteRouteWithChildren
  authenticatednewUserRouterRoute: typeof authenticatednewUserRouterRoute
  authenticatednewUserWelcomeIndexRoute: typeof authenticatednewUserWelcomeIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedexistingUserRouteRoute:
    authenticatedexistingUserRouteRouteWithChildren,
  authenticatednewUserRouterRoute: authenticatednewUserRouterRoute,
  authenticatednewUserWelcomeIndexRoute: authenticatednewUserWelcomeIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface guestRouteRouteChildren {
  guestSigninIndexRoute: typeof guestSigninIndexRoute
}

const guestRouteRouteChildren: guestRouteRouteChildren = {
  guestSigninIndexRoute: guestSigninIndexRoute,
}

const guestRouteRouteWithChildren = guestRouteRoute._addFileChildren(
  guestRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicCoursesIndexRoute: typeof publicCoursesIndexRoute
  publicPrivacyPolicyIndexRoute: typeof publicPrivacyPolicyIndexRoute
  publicRefundPolicyIndexRoute: typeof publicRefundPolicyIndexRoute
  publicTermsAndConditionsIndexRoute: typeof publicTermsAndConditionsIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicCoursesIndexRoute: publicCoursesIndexRoute,
  publicPrivacyPolicyIndexRoute: publicPrivacyPolicyIndexRoute,
  publicRefundPolicyIndexRoute: publicRefundPolicyIndexRoute,
  publicTermsAndConditionsIndexRoute: publicTermsAndConditionsIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  guestRouteRoute: guestRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
